* Emacs bindings for Tridactyl
Starting point for customizing Tridactyl to mimic Emacs

** Installation
First thing you need to change default Firefox bindings like Ctrl-N. It is impossible to change or disable that bindings, but you can change the modifier key used in that bindings instead. Go to about:config page and set ui.key.accelKey to 91 (WinKey). You can find more keycodes here - [[https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode]], but seems like WinKey is optimal choice because both Ctrl- and Alt- bindings are needed. 

Install Firefox extension [[https://github.com/tridactyl/tridactyl][Tridactyl]]. Then you need to install native messenger - it is necessary to be able to use config files. In Tridactyl enter to command mode (Shift-:), enter command "installnative" and follow instructions you'll receive. 

Copy emacs_bindings to ~/.config/tirdactyl and add this string to your tridactylrc
#+begin_src 
source ~/.config/tridactyl/emacs_bindings
#+end_src
Also you can just copy file content to your config directly.

** Contributions
Are welcome! I think of these bindings as a base to someone's own customization, but if I missed some common default binding, or some nice trick - please open PR/issue!
